version: '3.9'

services:

  tree-coded-menu:
    container_name: tree-coded-menu
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint: ["/app/docker-entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - "8003:8003"
    env_file:
      - ./.env
    depends_on:
      - menu-postgres
    networks:
      - menu-network

  menu-postgres:
    container_name: menu-postgres
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - menu-network

volumes:
  postgres_data:

networks:
  menu-network:
