# Generated by Django 5.1.2 on 2024-10-21 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="Может быть задан явным образом или как именованный URL",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "named_url",
                    models.CharField(
                        blank=True,
                        help_text="Именованный URL (например, 'main:index')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "menu_name",
                    models.CharField(
                        help_text="Название меню, чтобы различать несколько меню на странице", max_length=50
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="tree_coded_menu.menuitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт меню",
                "verbose_name_plural": "Пункты меню",
            },
        ),
    ]
